[features]
seeds = true
skip-lint = false

[programs.localnet]
legacy_vault = "7h9BH7d9aHGuPubFc6s9GCYDwtWrFNGB8kKKKV8YaSAe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
