// state/vault.rs
//
// The VaultAccount is the central on-chain record for a single inheritance
// vault. It is a PDA owned by the Legacy Vault program, meaning only the
// program's instructions can mutate it — no external wallet can sign on its
// behalf.
//
// Cloak integration changes (v2):
//   - `beneficiary` field replaced by `beneficiary_utxo_pubkey: [u8;32]`.
//     This stores a Cloak UTXO public key (32 raw bytes), NOT a Solana wallet.
//     For non-shielded vaults (backward compat), the beneficiary's wallet
//     pubkey bytes are stored here — they round-trip correctly via
//     Pubkey::from(bytes).
//   - `utxo_commitment: [u8;32]` — Poseidon commitment of the shielded UTXO.
//     Zero-bytes means no shielded deposit has been recorded.
//   - `utxo_leaf_index: u64` — leaf index in Cloak's Merkle tree. Zero until
//     record_cloak_deposit is called.
//   - `deposited_lamports` continues to track the vault balance. For shielded
//     vaults this is the owner's declared shielded amount — it is NOT
//     verifiable from on-chain SOL balance (which stays at rent-exempt minimum
//     because all SOL flows through Cloak).

use anchor_lang::prelude::*;
use crate::constants::VAULT_ACCOUNT_SIZE;

#[account]
pub struct VaultAccount {
    /// Wallet that created this vault and is allowed to check in, configure
    /// thresholds, add guardians, and close the vault.
    pub owner: Pubkey,

    /// 32-byte Cloak UTXO public key for the beneficiary.
    ///
    /// This is NOT a Solana wallet pubkey. It is the public half of the UTXO
    /// keypair generated by the beneficiary using `generateUtxoKeypair()` from
    /// the Cloak SDK. Only the beneficiary knows the corresponding private key.
    ///
    /// For non-shielded vaults (legacy mode), this stores the raw bytes of the
    /// beneficiary's Solana wallet pubkey so that `claim_inheritance` can still
    /// verify identity via `Pubkey::from(vault.beneficiary_utxo_pubkey)`.
    ///
    /// Stored as raw bytes (not Pubkey) to accommodate Cloak's curve arithmetic
    /// which uses a different encoding than Solana's Ed25519 addresses.
    pub beneficiary_utxo_pubkey: [u8; 32],

    /// Number of guardian accounts currently registered and active.
    pub guardian_count: u8,

    /// Minimum number of guardian signatures required to execute any covenant.
    /// Invariant: 1 ≤ m_of_n_threshold ≤ guardian_count (when guardian_count > 0).
    pub m_of_n_threshold: u8,

    /// How long the owner must be silent before the vault becomes claimable,
    /// measured in Solana slots (~2 slots/second).
    pub inactivity_threshold_slots: u64,

    /// The slot number of the owner's most recent check-in. This is the anchor
    /// point for all inactivity calculations.
    pub last_check_in_slot: u64,

    /// The slot at which this vault was initialised. Used for auditing and to
    /// seed the first activity interval.
    pub created_slot: u64,

    /// Total lamports declared as shielded. For Cloak vaults, this is the
    /// amount the owner recorded via `record_cloak_deposit`. The SOL itself
    /// resides in Cloak's shielded pool, not in this PDA — the on-chain
    /// balance of this PDA stays at rent-exempt minimum.
    ///
    /// For non-shielded vaults, this tracks the lamports actually held in
    /// this PDA (same semantics as before Cloak integration).
    pub deposited_lamports: u64,

    /// Monotonically increasing counter used to derive unique covenant PDAs.
    pub covenant_counter: u64,

    /// The index used when deriving this vault's PDA. Allows one owner to
    /// maintain multiple vaults simultaneously.
    pub vault_index: u64,

    /// Poseidon commitment of the shielded UTXO recorded by `record_cloak_deposit`.
    /// All zeros means this vault has no shielded deposit recorded yet.
    ///
    /// This commitment is the cryptographic proof that the vault owner
    /// deposited into Cloak. It cannot be forged without knowledge of the
    /// UTXO private key. Block explorers show only this 32-byte hash — not
    /// the balance, not the depositor, not the beneficiary.
    pub utxo_commitment: [u8; 32],

    /// Leaf index of the shielded UTXO in Cloak's Merkle tree.
    /// Used by guardians to retrieve the correct UTXO object during
    /// inheritance execution. Zero until `record_cloak_deposit` is called.
    pub utxo_leaf_index: u64,

    /// Set to true once `trigger_inheritance` succeeds. After this point the
    /// owner can no longer check in or modify vault parameters.
    pub is_triggered: bool,

    /// Set to true once the beneficiary has successfully claimed (either via
    /// `claim_inheritance` for non-shielded vaults, or `record_cloak_claim`
    /// after a shielded transfer).
    pub is_claimed: bool,

    /// Set to true once an emergency sweep has drained the vault.
    pub is_emergency_swept: bool,

    /// Tracks whether the 75% warning event has been emitted.
    pub warning_75_sent: bool,

    /// Tracks whether the 90% warning event has been emitted.
    pub warning_90_sent: bool,

    /// The canonical bump seed for this PDA, saved at initialisation.
    pub bump: u8,
}

impl VaultAccount {
    pub const LEN: usize = VAULT_ACCOUNT_SIZE;

    /// Returns true if this vault has a shielded deposit recorded.
    /// A zero utxo_commitment means no Cloak deposit has been made yet.
    pub fn is_shielded(&self) -> bool {
        self.utxo_commitment != [0u8; 32]
    }
}
